name: New Relic Synthetics

on: [push]

env:
  NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}

jobs:
  sync_synthetic_monitors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Changed Scripts
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          separator: ","
          files: |
            **/*.js
          json: "true"

      - name: Store Changed Scripts
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo ${{ steps.changed-files.outputs.all_changed_files }} > monitors.json
          cat monitors.json

      - name: Sync Changes to Synthetics
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: newrelic-experimental/synthetics-sync
        # with: # all optional defaults for creation of new scripts committed
        #   accountId: 1
        #   runtime: "new"
        #   privateLocations: "[{'guid': '...'}]"
        #   publicLocations: "['AWS_AP_EAST_1', 'AWS_US_EAST_2']"
        #   interval: EVERY_15_MINUTES
        #   status: ENABLED
