name: New Relic Synthetics

on:
  push:
    branches:
      - main

jobs:
  sync_synthetic_monitors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Changed Scripts
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            **/*.js
          json_raw_format: "true"

      - name: Extract FileNames and Script #Use custom python here to parse files, run entitySearch, and upload to NR
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo $GITHUB_WORKSPACE
          for file in $GITHUB_WORKSPACE/${{steps.changed-files.outputs.all_changed_files}}; do
            echo "File: $file"
            cat "$file"
          done
