name: New Relic Synthetics

on:
  push:
    branches:
      - main

jobs:
  sync_synthetic_monitors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Changed Scripts
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          separator: ","
          files: |
            **/*.js

      - name: Extract FileNames and Script #Use custom python here to parse files, run entitySearch, and upload to NR
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo $GITHUB_WORKSPACE
          IFS=$',' read -a CHANGED_SCRIPTS <<< "${{ steps.changed-files.outputs.all_changed_files }}"
          monitorNames=()
          scripts=()
          for file in "${CHANGED_SCRIPTS[@]}"; do
            monitorNames+=$file
            script=$(cat "$GITHUB_WORKSPACE/$file")
            scripts+=$script
          done
          echo $monitorNames
          echo $scripts
          unset IFS
        shell:
          bash
