name: New Relic Synthetics

on:
  push:
    branches:
      - main

jobs:
  sync_synthetic_monitors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Changed Scripts
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            **/*.js
          json: "true"

      - name: Extract FileNames and Script #Use custom python here to parse files, run entitySearch, and upload to NR
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo ${{steps.changed-files.outputs.all_changed_files}}
          changed_files=(${{steps.changed-files.outputs.all_changed_files}})
          filenames=()
          contents=()
          for file in "${changed_files[@]}"
          do
            monitorName=$(echo basename ${file%.*} | sed "s/.*\///")
            echo $monitorName
            filename=$(basename "$file")
            filenames+=("$filename")
            content=$(cat "$file")
            contents+=("$content")
          done
          echo "File names: ${filenames[@]}"
          echo "File contents: ${contents[@]}"
