name: New Relic Synthetics

on:
  push:
    branches:
      - main

env:
  NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}

jobs:
  sync_synthetic_monitors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Changed Scripts
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            **/*.js
          json: "true"

      - name: Extract FileNames and Script #Use custom python here to parse files, run entitySearch, and upload to NR
        id: scripts
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo ${{ steps.changed-files.outputs.all_changed_files }} > monitors.json
          cat monitors.json
